### ISSUE TITLE
importing sure before importing rethinkdb blows everything up!

### ISSUE THREAD

**Issue by clarete** [gabrielfalcao/sure#44] opened 2014-01-23 20:26 UTC
![image](https://f.cloud.github.com/assets/1459190/1988762/9eeaefb0-846c-11e3-8939-dfc35c8e9e59.png)

here's the text version of the traceback to help search engines to index the problem:

```python
>>> import sure
>>> import rethinkdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/canary/lib/python2.7/site-packages/rethinkdb/__init__.py", line 7, in <module>
    import rethinkdb.docs
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/canary/lib/python2.7/site-packages/rethinkdb/docs.py", line 19, in <module>
    rethinkdb.ast.RqlQuery.do.__func__.__doc__ = u"    Evaluate the expr in the context of one or more value bindings.\nThe type of the result is the type of the value returned from expr.\n\n *Example:* The object(s) passed to do() can be bound to name(s). The\nlast argument is the expression to evaluate in the context of the\nbindings.\n>>> r.do(r.table('marvel').get('IronMan'),\n...     lambda ironman: ironman['name']).run(conn)"
  File "/Users/lincoln/Work/Personal/dotfiles/.virtualenvs/canary/lib/python2.7/site-packages/sure/__init__.py", line 454, in __getattr__
    return super(AssertionBuilder, self).__getattribute__(attr)
AttributeError: 'AssertionBuilder' object has no attribute '__func__'
```

**Comment by timofurrer** [comment] 2016-06-21 05:36
I'm not able to reproduce your issue.

I tested with:

- `sure (1.3.0)`
- `rethinkdb (2.3.0.post4)`

... on both `python 2.7` and `python 3.5`.

It would be cool if you could double check with the newest version of `sure`.

**Comment by timofurrer** [comment] 2016-06-22 03:46
I'm closing this issue for now because I was not able to reproduce it. 
If you have the time to test if the newest version still has this issue, please let me know and I'll reopen this one.

**Closed by timofurrer** 2016-06-22 03:46 UTC
Labels: investigate
